<?php

class capTableSeeder extends Seeder {
    public function run()
    {
        
        DB::table('all_assets')->insert(array(
            
            array(
                'id' => 2,
                'name' => NULL,
                'asset_type' => 'Portable Radio',
                'model' => 'pr-23392',
                'make' => 'Motorola',
                'manu' => NULL,
                'serial_number' => 123456789,
                'model_imei' => NULL,
                'date_purchased' => '2016-10-12',
                'warranty_date' => NULL,
                'cost' => 50000,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => 'please change vendor names to realistic ones',
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => 'long range radio',
                'tier_level' => NULL,
                'system_alias' => 'rig_5 radio',
                'system_id' => 12,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-11 00:11:38',
                'updated_at' => '2016-11-17 22:41:54',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => 2,
                'vehicle_id' => 5,
                'vendor_id' => 22,
                'station_id' => NULL,
            ),

            array(
                'id' => 3,
                'name' => NULL,
                'asset_type' => 'Dock',
                'model' => 'zxzxz',
                'make' => NULL,
                'manu' => 'zxzxz',
                'serial_number' => 'zzxz',
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-11 00:15:44',
                'updated_at' => '2016-11-17 03:22:54',
                'deleted_at' => '2016-11-17 03:22:54',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 4,
                'name' => NULL,
                'asset_type' => 'Mobile Computer',
                'model' => NULL,
                'make' => NULL,
                'manu' => NULL,
                'serial_number' => 1111111111,
                'model_imei' => 0,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => 0,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => 0,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-11 00:30:39',
                'updated_at' => '2016-11-16 05:38:13',
                'deleted_at' => '2016-11-16 05:38:13',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 5,
                'name' => NULL,
                'asset_type' => 'Laptop',
                'model' => NULL,
                'make' => NULL,
                'manu' => NULL,
                'serial_number' => 11111111,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => 111133335555,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => 0,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-11 00:31:13',
                'updated_at' => '2016-11-16 05:38:19',
                'deleted_at' => '2016-11-16 05:38:19',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 7,
                'name' => 9898,
                'asset_type' => 'Laptop',
                'model' => 9898,
                'make' => NULL,
                'manu' => 9898,
                'serial_number' => 98998,
                'model_imei' => NULL,
                'date_purchased' => '2016-10-16',
                'warranty_date' => NULL,
                'cost' => 9898,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => 9898,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => 988,
                'ram' => 9898,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => 9898,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-14 04:14:35',
                'updated_at' => '2016-11-17 03:23:08',
                'deleted_at' => '2016-11-17 03:23:08',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 8,
                'name' => NULL,
                'asset_type' => 'Cad',
                'model' => NULL,
                'make' => NULL,
                'manu' => 'kkj',
                'serial_number' => NULL,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => 'kjjkkj',
                'mdc_pass' => 'kj',
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-14 04:20:12',
                'updated_at' => '2016-11-17 03:23:00',
                'deleted_at' => '2016-11-17 03:23:00',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 9,
                'name' => NULL,
                'asset_type' => 'Cad',
                'model' => NULL,
                'make' => NULL,
                'manu' => NULL,
                'serial_number' => NULL,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => 'fdfdfdgfd',
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-15 00:08:53',
                'updated_at' => '2016-11-16 16:04:23',
                'deleted_at' => '2016-11-16 16:04:23',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 10,
                'name' => NULL,
                'asset_type' => 'HPD',
                'model' => 'HPD 1000',
                'make' => 'Motorola',
                'manu' => NULL,
                'serial_number' => '153CJV0205',
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => '2017-02-15',
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => '10.4.5.123',
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => 10,
                'radio_id' => 4456,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-15 00:28:24',
                'updated_at' => '2016-11-17 22:05:42',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 11,
                'name' => NULL,
                'asset_type' => 'Cad',
                'model' => NULL,
                'make' => NULL,
                'manu' => 'fddsaf',
                'serial_number' => NULL,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => 'id_mdc_we_are_the',
                'mdc_pass' => 'test',
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-15 00:37:00',
                'updated_at' => '2016-11-17 03:23:14',
                'deleted_at' => '2016-11-17 03:23:14',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 12,
                'name' => 'BAT 1',
                'asset_type' => 'IPad',
                'model' => 'AirPad 2',
                'make' => 'Apple',
                'manu' => NULL,
                'serial_number' => 'DLXQ11TJG5YP',
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => 'ipad for medic units, using its 3rd charger',
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => 2,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => 4023784546,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => 89148000001844400000,
                'emid' => 356969062471434,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-16 04:53:05',
                'updated_at' => '2016-11-17 04:07:23',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 13,
                'name' => NULL,
                'asset_type' => 'Computer Monitor',
                'model' => 'E221',
                'make' => NULL,
                'manu' => NULL,
                'serial_number' => 123456,
                'model_imei' => NULL,
                'date_purchased' => '2016-02-01',
                'warranty_date' => NULL,
                'cost' => 300,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => 22,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-16 05:22:16',
                'updated_at' => '2016-11-22 00:25:24',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 14,
                'name' => 'FIRE-ADMN-D026',
                'asset_type' => 'Desktop Computer',
                'model' => 'Optiplex 760',
                'make' => 'Dell',
                'manu' => NULL,
                'serial_number' => 'FIRE-ADMN-D026',
                'model_imei' => NULL,
                'date_purchased' => '2014-07-20',
                'warranty_date' => NULL,
                'cost' => 1353,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => 'windows 7',
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => '10.3.1.125',
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => 'Dual 3.0 Ghz',
                'ram' => '4 gb',
                'asset_tag' => 'OFD-214123134',
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-16 05:24:35',
                'updated_at' => '2016-11-17 05:15:05',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 15,
                'name' => NULL,
                'asset_type' => 'InMotion',
                'model' => 100,
                'make' => NULL,
                'manu' => 'Texas Instruments',
                'serial_number' => 'HS-4534',
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => 2147483647,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => 'IMEI has letter in it, need to change the datatype, add as an issue at the Yodiz',
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => '0024E60051EC',
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => '3.1.4.2',
                'radio_id' => NULL,
                'meid_model_num' => 362,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-16 05:27:36',
                'updated_at' => '2016-11-17 04:20:51',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 16,
                'name' => NULL,
                'asset_type' => 'X-Series',
                'model' => NULL,
                'make' => NULL,
                'manu' => NULL,
                'serial_number' => 'SN-123210931231234',
                'model_imei' => NULL,
                'date_purchased' => '2013-12-01',
                'warranty_date' => NULL,
                'cost' => 1900,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-16 05:44:32',
                'updated_at' => '2016-11-17 03:23:36',
                'deleted_at' => '2016-11-17 03:23:36',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 17,
                'name' => NULL,
                'asset_type' => 'Team Viewer',
                'model' => NULL,
                'make' => NULL,
                'manu' => NULL,
                'serial_number' => NULL,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => 'ofd_admin23',
                'ntm_pass' => 'dsfjXewr1',
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => 'TM190283',
                'tmv_alias' => 'tmv_12',
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-16 05:45:12',
                'updated_at' => '2016-11-17 03:23:21',
                'deleted_at' => '2016-11-17 03:23:21',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 18,
                'name' => 'pr1',
                'asset_type' => 'Printer',
                'model' => 1231,
                'make' => 'HP',
                'manu' => NULL,
                'serial_number' => 123123123123,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => 'g',
                'network_status' => 0,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-16 13:58:13',
                'updated_at' => '2016-11-16 16:04:35',
                'deleted_at' => '2016-11-16 16:04:35',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 19,
                'name' => NULL,
                'asset_type' => 'Cad',
                'model' => NULL,
                'make' => NULL,
                'manu' => 'B1',
                'serial_number' => NULL,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => 'fsdfdsfddsffd',
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => 'DD11',
                'mdc_pass' => 1122,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-16 16:01:40',
                'updated_at' => '2016-11-17 03:23:30',
                'deleted_at' => '2016-11-17 03:23:30',
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 20,
                'name' => NULL,
                'asset_type' => 'HPD',
                'model' => 'HPD-TS-1270',
                'make' => 'Texas Instruments',
                'manu' => NULL,
                'serial_number' => 312413431,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => '2017-07-31',
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => 'need firmware version update',
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => '192.231.23.15',
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => 'v2',
                'radio_id' => 'hpd_838120',
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-16 16:06:19',
                'updated_at' => '2016-11-16 21:55:51',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 21,
                'name' => 'OFD-EMS-MASTER',
                'asset_type' => 'Mobile Computer',
                'model' => 'Getac',
                'make' => 'V110',
                'manu' => NULL,
                'serial_number' => 'RF139V0199',
                'model_imei' => 0,
                'date_purchased' => '2014-04-05',
                'warranty_date' => NULL,
                'cost' => '$1,856',
                'imei' => 2147483647,
                'mobile_type' => 'ePCR',
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-17 03:37:07',
                'updated_at' => '2016-11-17 04:24:02',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 22,
                'name' => NULL,
                'asset_type' => 'Dock',
                'model' => '7160-0515-03',
                'make' => 'Gamber-Jonhson',
                'manu' => NULL,
                'serial_number' => 'C21314AAW010',
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-17 04:11:47',
                'updated_at' => '2016-11-17 04:25:18',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 23,
                'name' => NULL,
                'asset_type' => 'Netmotion',
                'model' => NULL,
                'make' => NULL,
                'manu' => NULL,
                'serial_number' => NULL,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => 'Engine21',
                'ntm_pass' => 'ofdeng29999',
                'ip_address' => '10.4.1.523',
                'mac' => NULL,
                'cad_ip' => '10.5.6.123',
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-17 04:13:07',
                'updated_at' => '2016-11-17 04:13:07',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 24,
                'name' => NULL,
                'asset_type' => 'Sim Card',
                'model' => NULL,
                'make' => NULL,
                'manu' => NULL,
                'serial_number' => NULL,
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => '166.156.103.237',
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => 89148000000000000000,
                'sim_phone' => '402-810-1133',
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-17 04:14:15',
                'updated_at' => '2016-11-17 04:14:15',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 25,
                'name' => NULL,
                'asset_type' => 'Trimble GPS Unit',
                'model' => 'Placer Gold',
                'make' => 'Trimble',
                'manu' => NULL,
                'serial_number' => 'X0123',
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => 'NEMA',
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-17 04:15:23',
                'updated_at' => '2016-11-17 04:46:34',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 26,
                'name' => NULL,
                'asset_type' => 'Multi-Tech Modem',
                'model' => 'MTD-EV3',
                'make' => NULL,
                'manu' => NULL,
                'serial_number' => '5266496K',
                'model_imei' => NULL,
                'date_purchased' => NULL,
                'warranty_date' => NULL,
                'cost' => NULL,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => NULL,
                'ntm_pass' => NULL,
                'ip_address' => NULL,
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => 'E362',
                'meid' => 'A1000032B3EC85',
                'phone' => '402-619-3849',
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => NULL,
                'network_status' => NULL,
                'drop_status' => NULL,
                'switch_serial' => NULL,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-17 04:17:22',
                'updated_at' => '2016-11-17 04:54:34',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

            array(
                'id' => 27,
                'name' => 'NPI2250CE',
                'asset_type' => 'Printer',
                'model' => 'LaserJet 200 color M251nw',
                'make' => 'HP',
                'manu' => NULL,
                'serial_number' => 'VNB3B29207',
                'model_imei' => NULL,
                'date_purchased' => '2015-04-08',
                'warranty_date' => NULL,
                'cost' => 1403,
                'imei' => NULL,
                'mobile_type' => NULL,
                'os' => NULL,
                'comments' => NULL,
                'ntm_uid' => 'Chief Ausdemore',
                'ntm_pass' => NULL,
                'ip_address' => '10.3.1.236',
                'mac' => NULL,
                'cad_ip' => NULL,
                'sim_id' => NULL,
                'sim_phone' => NULL,
                'gps_protocol' => NULL,
                'firmware_ver' => NULL,
                'radio_id' => NULL,
                'meid_model_num' => NULL,
                'meid' => NULL,
                'phone' => NULL,
                'multi_tech_sim' => NULL,
                'mdc_id' => NULL,
                'mdc_pass' => NULL,
                'cpu' => NULL,
                'ram' => NULL,
                'asset_tag' => 'MPC468',
                'network_status' => 0,
                'drop_status' => 'Yes',
                'switch_serial' => 2153279000720,
                'screen_size' => NULL,
                'ac_adapter' => NULL,
                'stylus' => NULL,
                'seid_num' => NULL,
                'emid' => NULL,
                'tmv_num' => NULL,
                'tmv_alias' => NULL,
                'radio_desc' => NULL,
                'tier_level' => NULL,
                'system_alias' => NULL,
                'system_id' => NULL,
                'asset_document' => NULL,
                'asset_image' => NULL,
                'created_at' => '2016-11-17 04:22:25',
                'updated_at' => '2016-11-17 18:56:29',
                'deleted_at' => NULL,
                'personnel_id' => NULL,
                'status_id' => NULL,
                'vehicle_id' => NULL,
                'vendor_id' => NULL,
                'station_id' => NULL,
            ),

        ));
        DB::table('asset_grant')->insert(array(
            
            array(
                'id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'grant_id' => 1,
                'all_asset_id' => NULL,
                'station_id' => NULL,
                'vehicle_id' => 9,
            ),

            array(
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'grant_id' => 2,
                'all_asset_id' => NULL,
                'station_id' => NULL,
                'vehicle_id' => 4,
            ),

        ));
        DB::table('grants')->insert(array(
            
            array(
                'id' => 1,
                'grant_name' => 'Federal Grant',
                'date_issued' => '2017-04-29',
                'grant_type' => 'Federal Government',
                'date_matures' => '2018-11-01',
                'grant_value' => 2500000.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-02 05:36:01',
                'updated_at' => '2016-11-03 23:23:04',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 2,
                'grant_name' => 'Sarpy County',
                'date_issued' => '2016-11-12',
                'grant_type' => 'Functional ',
                'date_matures' => '2016-11-10',
                'grant_value' => 90000.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-03 23:20:49',
                'updated_at' => '2016-11-16 23:43:55',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 3,
                'grant_name' => 'Omaha ',
                'date_issued' => '2016-11-07',
                'grant_type' => 'Technical ',
                'date_matures' => '2016-11-30',
                'grant_value' => 700000.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-03 23:24:09',
                'updated_at' => '2016-11-04 00:01:32',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 4,
                'grant_name' => 'South Omaha Renovation',
                'date_issued' => '2016-12-01',
                'grant_type' => 'Functional ',
                'date_matures' => '2017-03-09',
                'grant_value' => 1000000.00,
                'grant_comments' => 'Followup with Federal Contractor',
                'created_at' => '2016-11-03 23:31:21',
                'updated_at' => '2016-11-07 22:00:51',
                'deleted_at' => '2016-11-07 22:00:51',
            ),

            array(
                'id' => 5,
                'grant_name' => 'Omaha ',
                'date_issued' => '2016-11-07',
                'grant_type' => 'Technical ',
                'date_matures' => '2016-11-30',
                'grant_value' => 700000.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-03 23:39:52',
                'updated_at' => '2016-11-16 03:54:36',
                'deleted_at' => '2016-11-16 03:54:36',
            ),

            array(
                'id' => 6,
                'grant_name' => 'Nebraska ',
                'date_issued' => '2016-08-25',
                'grant_type' => 'Technical ',
                'date_matures' => '2018-08-19',
                'grant_value' => 60001.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-03 23:59:06',
                'updated_at' => '2016-11-16 23:44:15',
                'deleted_at' => '2016-11-16 23:44:15',
            ),

            array(
                'id' => 7,
                'grant_name' => 'state fund',
                'date_issued' => '2016-11-09',
                'grant_type' => 'state',
                'date_matures' => '2016-11-09',
                'grant_value' => 10000.00,
                'grant_comments' => 'Douglas and Sarpy County Joint Commissioning Project - Followup Monthly',
                'created_at' => '2016-11-07 21:55:39',
                'updated_at' => '2016-11-16 23:44:22',
                'deleted_at' => '2016-11-16 23:44:22',
            ),

            array(
                'id' => 8,
                'grant_name' => 'Federal Grant 2',
                'date_issued' => '2016-11-21',
                'grant_type' => 'Federal Government',
                'date_matures' => '2016-11-02',
                'grant_value' => 1500000.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-07 21:56:38',
                'updated_at' => '2016-11-17 03:00:05',
                'deleted_at' => '2016-11-17 03:00:05',
            ),

            array(
                'id' => 15,
                'grant_name' => 'State Grant',
                'date_issued' => '2016-11-16',
                'grant_type' => 'State',
                'date_matures' => '2016-11-30',
                'grant_value' => 1000000.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-17 03:04:02',
                'updated_at' => '2016-11-17 21:55:02',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 16,
                'grant_name' => 'Corporate Sponsorship',
                'date_issued' => '2016-11-30',
                'grant_type' => 'Corporate',
                'date_matures' => '2017-03-24',
                'grant_value' => 3000000.00,
                'grant_comments' => 'new grant',
                'created_at' => '2016-11-17 03:05:00',
                'updated_at' => '2016-11-17 03:05:00',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 17,
                'grant_name' => 'County Grant',
                'date_issued' => '2016-11-01',
                'grant_type' => NULL,
                'date_matures' => NULL,
                'grant_value' => 0.00,
                'grant_comments' => 'Dollar amount to be determined',
                'created_at' => '2016-11-17 16:42:37',
                'updated_at' => '2016-11-17 17:24:39',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 18,
                'grant_name' => 'Grant 2341',
                'date_issued' => '2016-11-22',
                'grant_type' => 'Federal',
                'date_matures' => '2016-11-30',
                'grant_value' => 1200000.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-17 21:54:06',
                'updated_at' => '2016-11-17 21:54:52',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 19,
                'grant_name' => 'State Grant2',
                'date_issued' => '2016-11-24',
                'grant_type' => 'State',
                'date_matures' => '2017-01-20',
                'grant_value' => 123333.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-17 22:39:23',
                'updated_at' => '2016-11-17 22:39:50',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 20,
                'grant_name' => 'AFG',
                'date_issued' => '2016-11-18',
                'grant_type' => 'Fire',
                'date_matures' => '2016-11-19',
                'grant_value' => 1000.00,
                'grant_comments' => NULL,
                'created_at' => '2016-11-17 22:39:47',
                'updated_at' => '2016-11-17 22:39:47',
                'deleted_at' => NULL,
            ),

        ));
        DB::table('stations')->insert(array(
            
            array(
                'id' => 1,
                'station_name' => 'Station 1',
                'station_number' => 1,
                'station_date' => '1967-03-31',
                'address' => '1516 Jackson St.',
                'city' => 'Omaha',
                'zipcode' => 68102,
                'district' => 'Douglas',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-02 05:29:29',
                'updated_at' => '2016-11-29 15:04:37',
                'deleted_at' => NULL,
                'grant_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 2,
                'station_name' => 'Station 3',
                'station_number' => 3,
                'station_date' => '2001-07-10',
                'address' => '3126 South 16th Street',
                'city' => 'Omaha',
                'zipcode' => 68108,
                'district' => 'Douglas',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-08 01:24:33',
                'updated_at' => '2016-11-29 15:05:26',
                'deleted_at' => NULL,
                'grant_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 3,
                'station_name' => 'Station 5',
                'station_number' => 5,
                'station_date' => '2016-11-15',
                'address' => '2209 Florence Blvd. ',
                'city' => 'Omaha',
                'zipcode' => 68110,
                'district' => 'data missing',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-16 05:35:03',
                'updated_at' => '2016-11-17 02:49:04',
                'deleted_at' => NULL,
                'grant_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 4,
                'station_name' => 'Training',
                'station_number' => 101,
                'station_date' => '2016-11-01',
                'address' => '11616 Rainwood Road ',
                'city' => 'Omaha',
                'zipcode' => 68142,
                'district' => 'data missing',
                'station_note' => NULL,
                'station_document' => '1479336165-MB Armstrong Enhancing Training Outcomes with Gamification Poster.pdf',
                'station_image' => '1479336165-01.gif',
                'created_at' => '2016-11-16 22:42:45',
                'updated_at' => '2016-11-17 02:49:53',
                'deleted_at' => NULL,
                'grant_id' => 8,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 5,
                'station_name' => 'FIU',
                'station_number' => 102,
                'station_date' => '2016-11-01',
                'address' => '3126 South 16th Street',
                'city' => 'Omaha',
                'zipcode' => 68108,
                'district' => 'Douglas',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-17 02:50:51',
                'updated_at' => '2016-11-17 02:50:51',
                'deleted_at' => NULL,
                'grant_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 6,
                'station_name' => 'Station 71',
                'station_number' => 71,
                'station_date' => '2016-11-16',
                'address' => '103 Main St.',
                'city' => 'Elkhorn',
                'zipcode' => 68022,
                'district' => 'Elkhorn',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-17 04:48:00',
                'updated_at' => '2016-11-17 04:48:00',
                'deleted_at' => NULL,
                'grant_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 7,
                'station_name' => 'Station 201',
                'station_number' => 201,
                'station_date' => '2016-11-16',
                'address' => '7520 Jackson Street 37',
                'city' => 'omaha',
                'zipcode' => 68114,
                'district' => 'OMA',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-17 04:53:00',
                'updated_at' => '2016-11-17 04:53:00',
                'deleted_at' => NULL,
                'grant_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 8,
                'station_name' => 'Station 202',
                'station_number' => 202,
                'station_date' => '2016-11-16',
                'address' => '7520 Jackson Street 37',
                'city' => 'omaha',
                'zipcode' => 68114,
                'district' => 'OMA',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-17 05:00:03',
                'updated_at' => '2016-11-17 05:00:03',
                'deleted_at' => NULL,
                'grant_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 9,
                'station_name' => 'Station 203',
                'station_number' => 203,
                'station_date' => '2016-11-16',
                'address' => '7520 Jackson Street 37',
                'city' => 'omaha',
                'zipcode' => 68114,
                'district' => 'OMA',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-17 15:46:31',
                'updated_at' => '2016-11-17 15:48:31',
                'deleted_at' => '2016-11-17 15:48:31',
                'grant_id' => 15,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 10,
                'station_name' => 'Station 204',
                'station_number' => 204,
                'station_date' => '2016-11-16',
                'address' => '7520 Jackson Street 37',
                'city' => 'omaha',
                'zipcode' => 68114,
                'district' => 'OMA',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-17 15:58:54',
                'updated_at' => '2016-11-17 15:58:54',
                'deleted_at' => NULL,
                'grant_id' => 15,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 11,
                'station_name' => 'Station 222',
                'station_number' => 222,
                'station_date' => '2016-11-26',
                'address' => '2402 ridgeview dr,',
                'city' => 'Omaha',
                'zipcode' => 54701,
                'district' => 'douglas',
                'station_note' => NULL,
                'station_document' => NULL,
                'station_image' => NULL,
                'created_at' => '2016-11-27 04:14:44',
                'updated_at' => '2016-11-27 04:15:37',
                'deleted_at' => NULL,
                'grant_id' => 16,
                'vendor_id' => NULL,
            ),

        ));
        DB::table('statuses')->insert(array(
            
            array(
                'id' => 1,
                'status' => 'Available',
                'created_at' => '2016-11-02 05:49:37',
                'updated_at' => '2016-11-17 02:11:09',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 2,
                'status' => 'Spare',
                'created_at' => '2016-11-16 15:08:21',
                'updated_at' => '2016-11-17 02:11:17',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 3,
                'status' => 'In-repair',
                'created_at' => '2016-11-16 15:08:48',
                'updated_at' => '2016-11-17 02:11:26',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 4,
                'status' => 'Deactivated',
                'created_at' => '2016-11-16 15:09:00',
                'updated_at' => '2016-12-05 09:29:02',
                'deleted_at' => '2016-12-05 09:29:02',
            ),

            array(
                'id' => 5,
                'status' => 'Disposed',
                'created_at' => '2016-11-16 15:09:11',
                'updated_at' => '2016-11-17 02:11:44',
                'deleted_at' => NULL,
            ),

        ));
        DB::table('unit_types')->insert(array(
            
            array(
                'id' => 1,
                'name' => 'RIG',
                'created_at' => '2016-11-09 19:24:19',
                'updated_at' => '2016-11-09 19:24:19',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 2,
                'name' => 'Medic',
                'created_at' => '2016-11-09 19:24:24',
                'updated_at' => '2016-11-17 02:58:25',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 3,
                'name' => 'Squad',
                'created_at' => '2016-11-17 02:57:02',
                'updated_at' => '2016-11-17 02:57:02',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 5,
                'name' => 'Engine',
                'created_at' => '2016-11-17 02:57:02',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),

            array(
                'id' => 6,
                'name' => 'Truck',
                'created_at' => '2016-11-17 02:57:02',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),

            array(
                'id' => 7,
                'name' => 'B/C',
                'created_at' => '2016-11-17 02:57:02',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),

            array(
                'id' => 8,
                'name' => 'Command Post',
                'created_at' => '2016-11-17 02:57:02',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),

            array(
                'id' => 9,
                'name' => 'Rescue',
                'created_at' => '2016-11-17 02:57:02',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),

            array(
                'id' => 10,
                'name' => 'Other',
                'created_at' => '2016-11-17 02:57:02',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),

        ));
        DB::table('users')->insert(array(
            
            array(
                'id' => 4,
                'name' => 'test',
                'username' => 'test',
                'email' => 'aorgodol@unomaha.edu',
                'password' => '$2y$10$bbdAHNdWU7LLgZRR0a2GDuvL1spsGlKzm2Rm4mEFhCmYj2MGeR086',
                'remember_token' => NULL,
                'created_at' => '2016-12-05 08:50:16',
                'updated_at' => '2016-12-05 08:50:16',
            )

        ));
        DB::table('vehiclehis')->insert(array(
            
            array(
                'id' => 1,
                'vehicle_id' => 9,
                'vehicle_number' => NULL,
                'van' => 121212121212121212,
                'make' => NULL,
                'model' => NULL,
                'year' => 0000,
                'created_at' => '2016-12-05 03:28:31',
                'updated_at' => '2016-12-05 03:28:31',
                'station_id' => NULL,
                'name' => NULL,
                'status_id' => NULL,
                'status' => NULL,
                'grant_id' => NULL,
                'grant_name' => NULL,
                'unittype_id' => NULL,
                'unittype_name' => NULL,
                'vendor_id' => NULL,
                'vendor_name' => NULL,
            ),

            array(
                'id' => 2,
                'vehicle_id' => 4,
                'vehicle_number' => NULL,
                'van' => 57322,
                'make' => 'Honda',
                'model' => 'Traktor',
                'year' => 0000,
                'created_at' => '2016-12-05 03:28:45',
                'updated_at' => '2016-12-05 03:28:45',
                'station_id' => NULL,
                'name' => NULL,
                'status_id' => NULL,
                'status' => NULL,
                'grant_id' => NULL,
                'grant_name' => NULL,
                'unittype_id' => NULL,
                'unittype_name' => NULL,
                'vendor_id' => NULL,
                'vendor_name' => NULL,
            ),

            array(
                'id' => 3,
                'vehicle_id' => 9,
                'vehicle_number' => NULL,
                'van' => 121212121212121212,
                'make' => NULL,
                'model' => NULL,
                'year' => 0,
                'created_at' => '2016-12-05 03:30:08',
                'updated_at' => '2016-12-05 03:30:08',
                'station_id' => 2,
                'name' => 'Station 3',
                'status_id' => 3,
                'status' => 'In-repair',
                'grant_id' => NULL,
                'grant_name' => NULL,
                'unittype_id' => NULL,
                'unittype_name' => NULL,
                'vendor_id' => 5,
                'vendor_name' => 'Ford',
            ),

        ));
        DB::table('vehicles')->insert(array(
            
            array(
                'id' => 1,
                'vehicle_number' => 1,
                'van' => 23231,
                'make' => 'Chevrolet',
                'model' => 150,
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-02 05:31:12',
                'updated_at' => '2016-11-17 03:15:36',
                'deleted_at' => NULL,
                'station_id' => NULL,
                'status_id' => NULL,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 2,
                'vehicle_number' => 40,
                'van' => 23421,
                'make' => 'Dodge',
                'model' => 150,
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-08 00:24:09',
                'updated_at' => '2016-11-17 04:29:06',
                'deleted_at' => NULL,
                'station_id' => NULL,
                'status_id' => NULL,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 3,
                'vehicle_number' => 30,
                'van' => 68341,
                'make' => 'Dodge',
                'model' => 'Caravan',
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-08 00:24:46',
                'updated_at' => '2016-11-17 03:16:28',
                'deleted_at' => NULL,
                'station_id' => NULL,
                'status_id' => NULL,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 4,
                'vehicle_number' => 29,
                'van' => 57322,
                'make' => 'Honda',
                'model' => 'Traktor',
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-08 00:25:45',
                'updated_at' => '2016-12-05 09:28:45',
                'deleted_at' => NULL,
                'station_id' => 4,
                'status_id' => 2,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 5,
                'vehicle_number' => 15,
                'van' => 'ADGJADRGDF-1242135-1234',
                'make' => 'Honda',
                'model' => 'Moped',
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-08 00:26:44',
                'updated_at' => '2016-11-17 03:16:34',
                'deleted_at' => NULL,
                'station_id' => NULL,
                'status_id' => NULL,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 6,
                'vehicle_number' => 42,
                'van' => 52345,
                'make' => 'Coach',
                'model' => 'Freightliner',
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-08 01:04:55',
                'updated_at' => '2016-11-17 03:16:54',
                'deleted_at' => NULL,
                'station_id' => NULL,
                'status_id' => NULL,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 7,
                'vehicle_number' => 32,
                'van' => 67142,
                'make' => 'Coach',
                'model' => 'Freightliner',
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-08 01:06:03',
                'updated_at' => '2016-11-17 03:16:44',
                'deleted_at' => NULL,
                'station_id' => NULL,
                'status_id' => NULL,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 8,
                'vehicle_number' => 51,
                'van' => 71526,
                'make' => 'Coach',
                'model' => 'Freightliner',
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-08 01:30:03',
                'updated_at' => '2016-11-17 03:16:48',
                'deleted_at' => NULL,
                'station_id' => NULL,
                'status_id' => NULL,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 9,
                'vehicle_number' => NULL,
                'van' => 121212121212121212,
                'make' => 'Ford Motors',
                'model' => 'Frieghtliner',
                'year' => 2010,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-16 17:28:57',
                'updated_at' => '2016-12-05 09:30:08',
                'deleted_at' => NULL,
                'station_id' => 2,
                'status_id' => 3,
                'unittype_id' => NULL,
                'vendor_id' => 5,
            ),

            array(
                'id' => 10,
                'vehicle_number' => NULL,
                'van' => 52340,
                'make' => 'Coach',
                'model' => 'Freightliner',
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-17 03:22:05',
                'updated_at' => '2016-11-17 03:22:05',
                'deleted_at' => NULL,
                'station_id' => NULL,
                'status_id' => NULL,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

            array(
                'id' => 11,
                'vehicle_number' => NULL,
                'van' => 'OFD-199482-19385024',
                'make' => 'Honda',
                'model' => 'Moped',
                'year' => 0,
                'vehicle_note' => NULL,
                'vehicle_document' => NULL,
                'vehicle_image' => NULL,
                'created_at' => '2016-11-24 18:08:59',
                'updated_at' => '2016-11-24 18:09:10',
                'deleted_at' => NULL,
                'station_id' => NULL,
                'status_id' => NULL,
                'unittype_id' => NULL,
                'vendor_id' => NULL,
            ),

        ));
        DB::table('vendors')->insert(array(
            
            array(
                'id' => 1,
                'vendor_name' => 'Huber Chevrolet',
                'vendor_address' => '894 Industrial Avenue 894, Omaha, NE',
                'vendor_web' => 'http://www.huberchevrolet.com',
                'vendor_phone' => '402-453-3500',
                'vendor_fax' => '402-453-1200',
                'vendor_tech_sup' => '888-991-5600',
                'vendor_rep' => 'Jane McConnell',
                'vendor_rep_phone' => '402-490-7823',
                'vendor_rep_phone_m' => '402-490-7823',
                'vendor_email' => 'jane.mcconnell@chevrolet.com',
                'created_at' => '2016-11-02 05:37:59',
                'updated_at' => '2016-11-29 00:35:31',
                'deleted_at' => '2016-11-29 00:35:31',
            ),

            array(
                'id' => 5,
                'vendor_name' => 'Atchley Ford',
                'vendor_address' => '2345 N. 90th St., Omaha, NE 68114',
                'vendor_web' => 'http://www.atchleyford.com',
                'vendor_phone' => '402-556-1200',
                'vendor_fax' => '402-556-1213',
                'vendor_tech_sup' => '888-999-1212',
                'vendor_rep' => 'John Diers',
                'vendor_rep_phone' => '402-556-1200 x6782',
                'vendor_rep_phone_m' => '402-556-1200',
                'vendor_email' => 'john.diers@atchleyford.com',
                'created_at' => '2016-11-07 21:27:24',
                'updated_at' => '2016-12-05 03:28:13',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 21,
                'vendor_name' => 'Dell Marketing LP',
                'vendor_address' => 'P.O. Box 534118',
                'vendor_web' => 'www.dell.com',
                'vendor_phone' => '1-800-981-3355',
                'vendor_fax' => '1-800-433-9527',
                'vendor_tech_sup' => '1-800-624-9896',
                'vendor_rep' => 'Shawn Tucker',
                'vendor_rep_phone' => '512-728-3500 x 45917',
                'vendor_rep_phone_m' => '512-934-2367',
                'vendor_email' => 'shawn_tucker@dell.com',
                'created_at' => '2016-11-17 03:46:47',
                'updated_at' => '2016-11-17 03:46:47',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 22,
                'vendor_name' => 'Midwest Technology Solutions',
                'vendor_address' => '2580 S 90th St # 2 , Omaha, NE 68113',
                'vendor_web' => 'http://mtsi.net/',
                'vendor_phone' => '402- 504-4437',
                'vendor_fax' => NULL,
                'vendor_tech_sup' => '402-504-4327',
                'vendor_rep' => 'Mr. Charles Liakos',
                'vendor_rep_phone' => '(402) 504-4437',
                'vendor_rep_phone_m' => NULL,
                'vendor_email' => 'cliakos@mtsi.net',
                'created_at' => '2016-11-17 03:56:08',
                'updated_at' => '2016-11-17 03:56:08',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 23,
                'vendor_name' => 'Sirius Computer Solutions Inc.',
                'vendor_address' => '14301 FNB Pkwy #400 Omaha, NE  68154',
                'vendor_web' => 'http://www.siriuscom.com/',
                'vendor_phone' => '402-965-2300',
                'vendor_fax' => NULL,
                'vendor_tech_sup' => '1-800-460-1237',
                'vendor_rep' => 'Joe Mertens (CEO)',
                'vendor_rep_phone' => NULL,
                'vendor_rep_phone_m' => NULL,
                'vendor_email' => NULL,
                'created_at' => '2016-11-17 04:10:58',
                'updated_at' => '2016-11-17 04:10:58',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 24,
                'vendor_name' => 'Eagle Software, Inc',
                'vendor_address' => '124 Indiana Avenue, Salina, Kansas 67401 ',
                'vendor_web' => 'https://eagleinc.com/',
                'vendor_phone' => '800-477-5432',
                'vendor_fax' => NULL,
                'vendor_tech_sup' => '800-477-5432',
                'vendor_rep' => 'Dan G. (Contact using Team Viewer)',
                'vendor_rep_phone' => NULL,
                'vendor_rep_phone_m' => NULL,
                'vendor_email' => 'support@eagleinc.com',
                'created_at' => '2016-11-17 04:21:14',
                'updated_at' => '2016-11-17 04:21:14',
                'deleted_at' => NULL,
            ),

            array(
                'id' => 25,
                'vendor_name' => 'Lexmark International, Inc.',
                'vendor_address' => '740 W. New Circle Road, Lexington, KY 40550',
                'vendor_web' => 'http://www.lexmark.com/',
                'vendor_phone' => '913-227-7000',
                'vendor_fax' => NULL,
                'vendor_tech_sup' => '800-539-6275',
                'vendor_rep' => 'Not Assigned',
                'vendor_rep_phone' => NULL,
                'vendor_rep_phone_m' => NULL,
                'vendor_email' => NULL,
                'created_at' => '2016-11-17 05:09:52',
                'updated_at' => '2016-11-17 05:09:52',
                'deleted_at' => NULL,
            ),

        ));
    }
}